### ISSUE TITLE
Simplified query language

### ISSUE THREAD

**Issue by FrankChen021** [FrankChen021/bithon#631]
```json
{
        "dataSource": "exception-metrics",
        "type": "timeseries",
        "fields": [
          "eventCount"
        ],
        "bucketCount": 30
      }
```

It's too verbose. Can be simplied by one expression such as:

```sql
-- time serieis
from exception-metrics where appName = 'test' select eventCount group by timestamp
from exception-metrics select eventCount group by timestamp(30)
from exception-metrics select eventCount group by timestamp(30), exceptionClass
from exception-metrics where eventCount group by timestamp(30), exceptionClass

-- groupBy
from exception-metrics select exceptionClass, eventCount by exceptionClass order by exceptionClass asc limit 10

--list
from exception-metrics select timestamp, instanceName, thread, message order by timestamp asc
```

There other two alternatives or references:
1. https://prql-lang.org/
2. PromSQL

**Comment by FrankChen021** [comment]
for timeseries,

```sql
group by interval(timestamp)
group by interval(timestamp, 30) -- field = timestamp, bucke count = 30
group by interval(timestamp, 30, 60) -- field = timestamp, bucket count = 30, minimal length is 60 seconds
```

for group by, the grouped field can be omitted in the SELECT clause
```sql
from exception-metrics select eventCount group by exceptionClass order by exceptionClass
```

**Comment by FrankChen021** [comment]
The filter can be in the last of the statement so that it simplifies the processing of user input
```sql
from exception-metrics select eventCount group by exceptionClass order by exceptionClass WHERE appName = 'test'
```

**Comment by FrankChen021** [comment]
Other things to do
1. ResultFormat supports columar format
2. The response of timeseries data follows the general response format to be more simple and flexible
3. the zero-fil can be optional at the client side

**Comment by FrankChen021** [comment]
To simply the processing at the FE, the server can turn this expression into original JSON object format.

**Comment by jalamari2018** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @rori4, @me-o, @linshengli, @asgeir-s, @heavilyinvolved, @jpzk, @rorypeck

**Comment by FrankChen021** [comment]
https://promlabs.com/promql-cheat-sheet/

**Comment by FrankChen021** [comment]
Extension:
1. percentage
2. size
3. durationExpression: '[' DURATION (, BUCKET_COUNT (, MIN_STEP)? )? ']'

**Comment by FrankChen021** [comment]
already supported in the alerting module
